
spring:
  datasource:
    # 1. URL ??: ???? ?? ?? ?? ??(127.0.0.1)? ??(3306)? ??
    # ? ?? ????? ?? ?? ??? ??? ??? ?? ?????.
    url: jdbc:mysql://127.0.0.1:3306/openwallet-db?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true

    # 2. ?? ??: Cloud SQL? ??? ??? ??
    username: openwallet
    password: openwallet1234

    # 3. ???? ??
    driver-class-name: com.mysql.cj.jdbc.Driver

  # (?? ??) JPA/Hibernate ??
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true      # ???? SQL ?? ??
    hibernate:
      ddl-auto: update  # ???: ??? ?? ???? (?? ????? validate ?? none ??)
    properties:
      hibernate:
        format_sql: true # SQL ??? ?? ?? ???

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus # ??? ? ??
  endpoint:
    health:
      probes:
        enabled: true # ? ?????? Liveness/Readiness ?? ?? ???
      show-details: always